= Changelog

[[release-0.17.1]]
== 0.17.1 (2025-02-10)

=== Fixes

* Fix a memory leak when loading a Pkl module (https://github.com/apple/pkl-spring/pull/11[#11]).
* Fix an issue when loading a file-based config source (https://github.com/apple/pkl-spring/pull/11[#11]).

=== Contributors ❤️

Thank you to all our contributors!

* https://github.com/protobufel2[@protobufel2]

[[release-0.17.0]]
== 0.17.0 (2025-01-24)

=== Changes

* Update to Pkl 0.27.0 (https://github.com/apple/pkl-spring/pull/6[#6]).
* Update samples to Spring Boot 3.x (https://github.com/apple/pkl-spring/pull/6[#6]).

[NOTE]
====
Starting with Pkl 0.27, Pkl's Java and Kotlin code generators target Spring Boot 3.

To use _pkl-spring_ with Spring Boot 3, the following requirements must be met:

* Config classes are generated with Pkl 0.27 or later.
  Typically, this is done by using version 0.27.0 or later of Pkl's Gradle plugin.
* (Java) Config classes are compiled with the `-parameters` compiler argument.
  Spring Boot's Gradle plugin handles this automatically.
* (Kotlin) Config classes are compiled with the `-java-parameters` compiler argument.
  Spring Boot's Gradle plugin handles this automatically.

To use _pkl-spring_ with Spring Boot 2, the following requirements must be met:

* Config classes are generated with Pkl 0.26 or earlier.
  Typically, this is done by using version 0.26.3 or earlier of Pkl's Gradle plugin.
====

=== Contributors ❤️

Thank you to all our contributors!

* https://github.com/odenix[@odenix]

[[release-0.16.0]]
== 0.16.0 (2024-06-17)

* Update to Pkl 0.26
* Update to Java 17

[[release-0.15.0]]
== 0.15.0 (2024-02-01)

Initial library release

